### ISSUE TITLE
404 on big-ip-common-commands and  traffic-generator-tools-cheatsheet links

### ISSUE THREAD

**Issue by bluejeans825** [f5devcentral/f5-professional-services#15]
Not sure if the links for the tips-and-tricks URIs are bad, or the content is protected but when I try to access them, I get a 404 from GITHUB

Also, I would want someone to tell me that the ancialliary word under Tips And Tricks needs to be corrected

`The tip-and-tricks folder contains common commands used day to day in F5 technologies as well as cheatsheet and tips (!) on various ancialliary` (*ancillary*) `tools.`

**Comment by f5regan** [comment]
Hi @bluejeans825, thanks for raising this issue. I have fixed the links and the spelling issue!
